import Link from "next/link";
import Meta from "../components/Meta";
import styles from "../styles/Home.module.css";

export default function Home({ users }) {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Meta
        title="Home"
        description="Generated by create next app"
        keyword="home, homejs"
      />
      <h1>This is next project</h1>
      {users.map((user) => (
        <Link key={user.id} href="/users/[id]" as={`/users/${user.id}`}>
          <div style={{ border: "1px solid red" }}>
            <h1>Name: {user.name}</h1>
            <h3>userName: {user.username}</h3>
          </div>
        </Link>
      ))}
    </div>
  );
}

// server side rendering
// export async function getServerSideProps() {
//   const res = await fetch("https://jsonplaceholder.typicode.com/users");
//   const users = await res.json();

//   return {
//     props: { users }, // will be passed to the page component as props
//   };
// }

// static side genaration
export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const users = await res.json();

  return {
    props: { users }, // will be passed to the page component as props
  };
}
